### ISSUE TITLE
Support https URLs in baseurl for mb test

### ISSUE THREAD

**Issue by lrupp** [openSUSE/mirrorbrain#27]
Copied fromhttps://github.com/poeml/mirrorbrain/issues/167

It's a subset of https://github.com/poeml/mirrorbrain/issues/143 but that should be easy to handle... just allow "https" URLs in the baseurl setting. Everything seems to work fine except "mb test" which fails like this:
```
Traceback (most recent call last):
  File "/usr/bin/mb", line 1677, in <module>
    r = mirrordoctor.main()
  File "/usr/lib/pymodules/python2.7/cmdln.py", line 257, in main
    return self.cmd(args)
  File "/usr/lib/pymodules/python2.7/cmdln.py", line 280, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/pymodules/python2.7/cmdln.py", line 412, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/pymodules/python2.7/cmdln.py", line 1100, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/bin/mb", line 499, in do_test
    r = mb.testmirror.access_http(mirror.identifier, mirror.baseurl)
  File "/usr/lib/pymodules/python2.7/mb/testmirror.py", line 17, in access_http
    S = Sample(identifier, url, '', get_content=True)
  File "/usr/lib/pymodules/python2.7/mb/util.py", line 60, in __init__
    raise Exception('unknown url type: %s' % self.probebaseurl)
Exception: unknown url type: https://archive-2.kali.org/kali-images/
```

And this is easily fixed in mb/util.py with a simple "or" clause allowing both "http://" and "https://" as prefix for the "http" scheme.

**Comment by andrii-suse** [comment]
I've tried to simply add https scheme but it looks ~python~ perl may have issues connecting over ssl : 

```
+ mb9/mb.sh new ap7 --http https://127.0.0.1:1304 --region NA --country us
ap7: adding network prefix: 127.0.0.1/32 (AS1231)
+ mb9/mb.sh scan --enable ap7
Wed May 13 10:53:10 2020 ap7: starting
Wed May 13 10:53:10 2020 ap7: total files before scan: 0
https://127.0.0.1:1304//?F=1: error "500 Can't connect to 127.0.0.1:1304 (SSL connect attempt failed error:1408F10B:SSL routines:ssl3_get_record:wrong version number)" fetching index, skipped.
Wed May 13 10:53:10 2020 ap7: scanned 0 files (0/s) in 0s
Wed May 13 10:53:10 2020 ap7: files to be purged: 0
Wed May 13 10:53:10 2020 ap7: total files after scan: 0 (delta: 0)
Wed May 13 10:53:10 2020 ap7: purged old files in 0s.
Wed May 13 10:53:10 2020 ap7: done.
Wed May 13 10:53:10 2020 ap7: testing status of base URL...
Wed May 13 10:53:10 2020 ap7: Error: base URL does not work: https://127.0.0.1:1304
Completed in 0 seconds
```

**Comment by andrii-suse** [comment]
This probably is not a problem though as log as --rsync parameter is present...

**Comment by andrii-suse** [comment]
So I've looked deeper and in current implementation even if rsync succeeds for https server - it still never will be used, because `status_baseurl` column remains 'false' in DB. So, I will have a look into how difficult is to teach mirrorprobe.py to connect to https addresses.
